
name: Conversion Request
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  get-pack-info:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'conversion'
    permissions: 
      issues: read
    timeout-minutes: 2
    outputs:
      pack_url: ${{ steps.organize-inputs.outputs.PACK_URL }}
      default_pack_url: ${{ steps.organize-inputs.outputs.DEFAULT_PACK_URL }}
      merge_pack_url: ${{ steps.organize-inputs.outputs.MERGE_PACK_URL }}
      default_assets_version: ${{ steps.organize-inputs.outputs.DEFAULT_ASSETS_VERSION }}
      block_material: ${{ steps.organize-inputs.outputs.BLOCK_MATERIAL }}
      attachable_material: ${{ steps.organize-inputs.outputs.ATTACHABLE_MATERIAL }}
      archive_scratch: ${{ steps.organize-inputs.outputs.ARCHIVE_SCRATCH }}
